version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    volumes:
      # Optional: Uncomment for persistent data storage
      # - ./dynamodb-data:/home/dynamodblocal/data
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    # For persistent storage, use this command instead:
    # command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "./data"]
    container_name: dynamodb-local
    restart: unless-stopped 