[project]
name = "gitlab-mcp"
version = "0.1.0"
description = "GitLab MCP Server for GitLab API operations"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.11.0",
    "requests>=2.32.4",
]